# Generated by Django 5.1.6 on 2025-05-27 17:12

import django.db.models.deletion
import django.utils.timezone
import fin_pull.models.fields.base
import fin_pull.models.fields.date
import fin_pull.models.fields.fk
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, max_length=127, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='HistoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, max_length=127, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'тип',
                'verbose_name_plural': 'типы',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, max_length=127, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'статус',
                'verbose_name_plural': 'статусы',
            },
        ),
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Признак активности записи')),
                ('category', fin_pull.models.fields.fk.CategoryFK(on_delete=django.db.models.deletion.PROTECT, to='fin_pull.category', verbose_name='Категория')),
                ('history_type', fin_pull.models.fields.fk.HistoryTypeFK(on_delete=django.db.models.deletion.PROTECT, to='fin_pull.historytype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'связь категории и типа',
                'verbose_name_plural': 'связи категорий и типов',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='history_type',
            field=models.ManyToManyField(related_name='categories', through='fin_pull.CategoryType', to='fin_pull.historytype'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, max_length=127, unique=True, verbose_name='Слаг')),
                ('category', fin_pull.models.fields.fk.CategoryFK(on_delete=django.db.models.deletion.PROTECT, to='fin_pull.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'подкатегория',
                'verbose_name_plural': 'подкатегории',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', fin_pull.models.fields.date.CreatedDate(default=django.utils.timezone.now, verbose_name='Дата создания записи')),
                ('amount', fin_pull.models.fields.base.Amount(default=0, verbose_name='Сумма средств')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('category', fin_pull.models.fields.fk.CategoryFK(on_delete=django.db.models.deletion.PROTECT, to='fin_pull.category', verbose_name='Категория')),
                ('history_type', fin_pull.models.fields.fk.HistoryTypeFK(on_delete=django.db.models.deletion.PROTECT, to='fin_pull.historytype', verbose_name='Тип')),
                ('status', fin_pull.models.fields.fk.StatusFK(on_delete=django.db.models.deletion.PROTECT, to='fin_pull.status', verbose_name='Статус')),
                ('subcategory', fin_pull.models.fields.fk.SubCategoryFK(on_delete=django.db.models.deletion.PROTECT, to='fin_pull.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'запись о ДДС',
                'verbose_name_plural': 'записи о ДДС',
            },
        ),
    ]
